### PR TITLE
Fix End-to-end tests for tracing

### LINKED ISSUE #91: Fix e2e-tests that deal with tracing

### PR DESCRIPTION
**Pull request by sappenin**
## High Level Overview of Change

Fixes #91 by updating `trace_escrow_account`, `trace_escrow_finish`, and `trace_escrow_ledger_object` to correctly emit all fields.

### CODE REVIEW

File: xrpl-wasm-stdlib/src/core/types/credentials.rs [hunk 1]
```diff
@@ -1,63 +1,47 @@
...
+///
+/// CredentialIDs are 256-bit hashes that uniquely identify credentials on the XRPL.
+/// They are computed from the credential's issuer, subject, and credential type.
 #[derive(Debug, Clone, Copy, Eq, PartialEq)]
 #[repr(C)]
-pub struct CredentialIDs {
-    pub credential_ids: [CredentialID; 10],
-    pub num_credential_ids: u8, // Max of 10!
-}
+pub struct CredentialID(pub [u8; 32]);
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/types/credentials.rs]: Good point. With this latest refactor, it doesn't seem to be doing much anymore. I removed it via 63439767db923624b1ccbf5a89c5dbcdca6cb470 and feel good about just using `Vector256`.

File: xrpl-wasm-stdlib/src/core/types/crypto_condition.rs [hunk 2]
```diff
@@ -1,40 +1,166 @@
...
+        }
     }
 }
 
-/// A crypto-condition Fulfillment. Note that from rippled source, this value is currently capped
-/// at 256 bytes, which allows us to treat it as such.
+/// The maximum number of bytes in a Fulfillment. Theoretically, the crypto-condition format allows for much larger
+/// fulfillments, but xrpld currently caps this value at 256 bytes (see `maxSerializedFulfillment` in xrpld source
+/// code), so we do the same here.
+pub const MAX_FULFILLMENT_SIZE: usize = 256;
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/types/crypto_condition.rs]: Also - separate PR: replace `Signature` with typedef. Search for other typedef's in blob.rs and use them in places where they could be used (e.g., look for `UriBlob` potential usages; look for all usages of Blob).

We'll merge that new PR first, and then incorporate into this PR once merged.

[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/types/crypto_condition.rs]: This PR is now ready for review. The blob changes in this PR are necessary for the e2e tests to pass. The rest of the blob refactoring can be found here: https://github.com/ripple/xrpl-wasm-stdlib/pull/100/files

File: xrpl-wasm-stdlib/src/core/current_tx/mod.rs [hunk 3]
```diff
@@ -65,11 +65,12 @@ use crate::core::types::public_key::PublicKey;
 use crate::core::types::signature::{SIGNATURE_MAX_SIZE, Signature};
 use crate::core::types::transaction_type::TransactionType;
 use crate::core::types::uint::{HASH256_SIZE, Hash256};
+use crate::core::types::vector_256::Vector256;
 use crate::host::error_codes::{
-    match_result_code, match_result_code_optional, match_result_code_with_expected_bytes,
+    self, match_result_code, match_result_code_optional, match_result_code_with_expected_bytes,
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/current_tx/mod.rs]: Fixed via f8f60137995e3089208d325ca4f76fe6a81edf4d

File: xrpl-wasm-stdlib/src/core/types/vector_256.rs [hunk 4]
```diff
@@ -0,0 +1,291 @@
...
+    /// Returns an error if:
+    /// - The buffer is too small
+    /// - The data length is not a multiple of 32
+    /// - The count exceeds MAX_VECTOR256_SIZE
+    /// - The buffer doesn't contain enough bytes for all hashes
+    pub fn from_bytes(bytes: &[u8]) -> crate::host::Result<Self> {
+        use crate::host::trace::{trace, trace_num};
+
+        let _ = trace("Vector256::from_bytes called");
+        let _ = trace_num("  bytes.len():", bytes.len() as i64);
```
Comment (mvadari) [inline xrpl-wasm-stdlib/src/core/types/vector_256.rs]: There shouldn't be any traces in the successful path. And minimal traces in the error paths.

Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/types/vector_256.rs]: Totally agreed, that was a remnant from me trying to debug something. Nice catch!

Fixed via ec7a423da593a54859313df67776c3cc297afa77

File: xrpl-wasm-stdlib/src/core/types/vector_256.rs [hunk 5]
```diff
@@ -0,0 +1,283 @@
...
+#[derive(Debug, Clone, Eq, PartialEq)]
+#[repr(C)]
+pub struct Vector256 {
+    /// The hash values
+    pub hashes: [Hash256; MAX_VECTOR_256_SIZE],
+    /// Number of valid hashes (0 to MAX_VECTOR256_SIZE)
+    pub len: u8,
+}
+
+impl Vector256 {
```
Comment (mvadari) [inline xrpl-wasm-stdlib/src/core/types/vector_256.rs]: I actually think this code is unnecessary and needs a rippled fix. This should be a type you should iterate through with a locator, instead of fetching the whole thing.

File: xrpl-wasm-stdlib/src/core/current_tx/mod.rs [hunk 6]
```diff
@@ -476,3 +544,173 @@ pub fn get_field_optional<T: CurrentTxFieldGetter>(field_code: i32) -> Result<Op
...
 pub mod escrow_finish;
 pub mod traits;
+
+#[cfg(test)]
+mod tests {
+    use super::*;
+    use crate::core::types::vector_256::MAX_VECTOR_256_SIZE;
+
+    #[test]
+    fn test_vector256_from_bytes_empty() {
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/core/current_tx/mod.rs]: Yep, these are removed now via 92be78d26fd9b8538c851c4477ca9d02aa8c227e

File: xrpl-wasm-stdlib/src/host/host_bindings_for_testing.rs [hunk 7]
```diff
@@ -673,7 +742,30 @@ pub unsafe fn trace_opaque_float(
     _opaque_float_ptr: *const u8,
     _opaque_float_len: usize,
 ) -> i32 {
-    // Prevent overflow: saturate addition and cast to i32 safely
+    // Read the message bytes from the pointer and convert to UTF-8 string
```
[the remark this answers is not in the document]
Comment (sappenin) [reply xrpl-wasm-stdlib/src/host/host_bindings_for_testing.rs]: Good suggestion - fixed via 47b6a80bf96af06b4406363b7552f8bb6872bea5

File: e2e-tests/trace_escrow_ledger_object/src/lib.rs [hunk 8]
```diff
@@ -37,100 +55,140 @@ pub extern "C" fn finish() -> i32 {
...
 
         // Trace Field: Destination
         let destination = current_escrow.get_destination().unwrap();
-        const EXPECTED_DESTINATION: [u8; 20] = [
-            0x3E, 0x9D, 0x4A, 0x2B, 0x8A, 0xA0, 0x78, 0x0F, 0x68, 0x2D, 0x13, 0x6F, 0x7A, 0x56,
-            0xD6, 0x72, 0x4E, 0xF5, 0x37, 0x54,
-        ];
-        assert_eq!(destination.0, EXPECTED_DESTINATION);
+        // Destination is set in runTest.js (destWallet), just verify it's a valid AccountID
+        #[cfg(target_arch = "wasm32")]
```
Comment (mvadari) [inline e2e-tests/trace_escrow_ledger_object/src/lib.rs]: Why not make this a part of the macro instead of needing to specify it every time?

File: e2e-tests/trace_escrow_ledger_object/README.md [hunk 9]
```diff
@@ -0,0 +1,46 @@
...
+```shell
+cd ../..
+./scripts/run-tests.sh e2e-tests/trace_escrow_ledger_object
+```
+
+### 3b. Deploy and test on Devnet
+
+```shell
+cd ../..
+CI=1 ./scripts/run-tests.sh e2e-tests/trace_escrow_ledger_object
```
Comment (mvadari) [inline e2e-tests/trace_escrow_ledger_object/README.md]:
```suggestion
DEVNET=true ./scripts/run-tests.sh e2e-tests/trace_escrow_ledger_object
```

File: e2e-tests/trace_escrow_ledger_object/src/lib.rs (hunk 8 above)
Comment (sappenin) [reply e2e-tests/trace_escrow_ledger_object/src/lib.rs]: Per our discussion today, I moved the macro into the `e2e-tests` folder so that nobody uses it accidentally in a real contract. See 63c3e7c760a1066ea5a610555e2d17f94e51ec1c

File: e2e-tests/Cargo.toml [hunk 10]
```diff
@@ -5,11 +5,16 @@ members = [
     "gas_benchmark",
     "host_functions_test",
     "keylet_exists",
+    "test-utils",
```
Comment (mvadari) [inline e2e-tests/Cargo.toml]: should probably use `snake_case` to match the rest of this workspace

File: e2e-tests/test-utils/Cargo.toml [hunk 11]
```diff
@@ -0,0 +1,12 @@
+[package]
+name = "test-utils"
+version = "0.5.1-devnet5"
+edition = "2024"
+description = "Test utilities for XRPL WASM e2e tests"
```
Comment (mvadari) [inline e2e-tests/test-utils/Cargo.toml]: Perhaps there should be some note here that this is a private package and won't/shouldn't be published to crates.io

File: e2e-tests/Cargo.toml (hunk 10 above)
Comment (sappenin) [reply e2e-tests/Cargo.toml]: > Also, does this need to be a member of the workspace?

Yeah, probably just for `cargo` to work.

File: e2e-tests/trace_escrow_finish/src/lib.rs [hunk 12]
```diff
@@ -188,10 +226,20 @@ pub extern "C" fn finish() -> i32 {
...
+                continue;
             }
             let _ = trace_num("    Signer #:", i as i64);
-            let _ = trace_account_buf("     Account:", &buf[..20].try_into().unwrap());
+            // Account should be 20 bytes
+            let _ = trace_num("     Account length:", output_len as i64);
+            if output_len == 20 {
+                let _ = trace_account_buf("     Account:", &buf[..20].try_into().unwrap());
+            } else {
+                let _ = trace_data(
```
[the remark this answers is not in the document]
Comment (sappenin) [reply e2e-tests/trace_escrow_finish/src/lib.rs]: Yes. Fixed via b3ad796b19aa270f07cfd0f833024ea103140edd

File: e2e-tests/trace_escrow_finish/src/lib.rs [hunk 13]
```diff
@@ -188,10 +226,20 @@ pub extern "C" fn finish() -> i32 {
             };
             if output_len < 0 {
                 let _ = trace_num("  cannot get Account, error:", output_len as i64);
-                panic!()
+                continue;
```
[the remark this answers is not in the document]
Comment (sappenin) [reply e2e-tests/trace_escrow_finish/src/lib.rs]: Good catch. Fixed via b3ad796b19aa270f07cfd0f833024ea103140edd
